default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: roOt@1234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: build_short_url_development
test:
  <<: *default
  database: build_short_url_test

production:
  <<: *default
  database: build_short_url_production
  username: build_short_url
  password: <%= ENV["BUILD_SHORT_URL_DATABASE_PASSWORD"] %>
